export const mockStocks = [
  { symbol: "ABBV", name: "AbbVie Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 150 },
  { symbol: "ABF", name: "Associated British Foods plc", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 2500 },
  { symbol: "AMT", name: "American Tower Corporation", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 220 },
  { symbol: "ARE", name: "Alexandria Real Estate Equities Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 140 },
  { symbol: "BATS", name: "British American Tobacco plc", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 2800 },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 65 },
  { symbol: "BAM", name: "Brookfield Asset Management Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 45 },
  { symbol: "CTRE", name: "CareTrust REIT Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 25 },
  { symbol: "CME", name: "CME Group Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 220 },
  { symbol: "KO", name: "The Coca-Cola Company", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 65 },
  { symbol: "DGE", name: "Diageo plc", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 3500 },
  { symbol: "FDS", name: "FactSet Research Systems Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 480 },
  { symbol: "JNJ", name: "Johnson & Johnson", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 175 },
  { symbol: "LOG", name: "Logistics Realty Corp.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 35 },
  { symbol: "MC", name: "LVMH Moët Hennessy Louis Vuitton SE", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 900 },
  { symbol: "LYB", name: "LyondellBasell Industries N.V.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 105 },
  { symbol: "MKTX", name: "MarketAxess Holdings Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 380 },
  { symbol: "MRK", name: "Merck & Co. Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 135 },
  { symbol: "TAP", name: "Molson Coors Beverage Company", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 70 },
  { symbol: "MNDI", name: "Mondi plc", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 1500 },
  { symbol: "MDLZ", name: "Mondelez International Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 80 },
  { symbol: "NHI", name: "National Health Investors Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 70 },
  { symbol: "NVO", name: "Novo Nordisk A/S", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 125 },
  { symbol: "PEP", name: "PepsiCo Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 190 },
  { symbol: "PETS", name: "Pets at Home Group plc", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 450 },
  { symbol: "SDR", name: "Schroders plc", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 400 },
  { symbol: "SWKS", name: "Skyworks Solutions Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 110 },
  { symbol: "O", name: "Realty Income Corporation", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 65 },
  { symbol: "TROW", name: "T. Rowe Price Group Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 135 },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 580 },
  { symbol: "VZ", name: "Verizon Communications Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 45 },
  { symbol: "VIS", name: "Viscofan S.A.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 55 },
  { symbol: "WPC", name: "W.P. Carey Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 75 },
  { symbol: "ZTS", name: "Zoetis Inc.", price: 0, change: 0, changePercent: 0, volume: "N/A", marketCap: "N/A", pe: 0, trend: [0, 0, 0, 0, 0, 0, 0], targetPrice: 220 },
] as const